image: node:latest

stages:
  - test
  - publish

cache:
  paths:
    - node_modules
    - package-lock.json

test:
  stage: test
  tags:
    - shared
  script:
    - npm install
    - npm test

publish:
  stage: publish
  only:
    - tags
    - /^v\d+\.\d+\.\d+-?.*$/
  script:
    - npm install
    - npm publish

