stages:
  - test
  - build
  - deploy

include:
  - project: hydra/dev/ci-templates
    file: /v1/static/publish.yml

test:
  image: node:latest
  stage: test
  tags:
    - shared
  script:
    - npm install
    - npm test

build publish:
  variables:
    GIT_STRATEGY: none
  script: echo job skipped
