image: node:latest

stages:
  - test
  - publish

cache:
  paths:
    - node_modules
    - package-lock.json

test:
  stage: test
  tags:
    - shared
  script:
    - npm install
    - npm test

publish:
  stage: publish
  only:
    - /^v\d+\.\d+\.\d+-?.*$/
  except:
    - branches
  script:
    - npm install
    - npm set //registry.npmjs.org/:_authToken="$NPM_PUBLISH_TOKEN";
    - npm publish
